// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFolder() {
  return window['go']['main']['App']['ChangeFolder']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function OnSecondInstance(arg1) {
  return window['go']['main']['App']['OnSecondInstance'](arg1);
}

export function OpenFolder() {
  return window['go']['main']['App']['OpenFolder']();
}

export function OpenLogs() {
  return window['go']['main']['App']['OpenLogs']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}
