// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {options} from '../models';

export function ChangeFolder():Promise<string>;

export function GetState():Promise<main.State>;

export function OnSecondInstance(arg1:options.SecondInstanceData):Promise<void>;

export function OpenFolder():Promise<void>;

export function OpenLogs():Promise<void>;

export function QuitApp():Promise<void>;
